blueprint:
  name: Tuya Zigbee 4 button remote
  description: "Blueprint para Tuya Zigbee 4 botões (TS0044_1) com Zigbee2MQTT baseado em eventos."
  domain: automation
  input:
    switch:
      name: Tuya Zigbee 4 button remote
      description: Tuya Zigbee 4 button remote a usar
      selector:
        entity:
    button_1_single:
      name: Single Press - Button 1
      description: Ação para botão 1 single press
      default: []
      selector:
        action: null
    button_1_double:
      name: Double Press - Button 1
      description: Ação para botão 1 double press
      default: []
      selector:
        action: null
    button_1_hold:
      name: Hold - Button 1
      description: Ação para botão 1 hold
      default: []
      selector:
        action: null
    button_2_single:
      name: Single Press - Button 2
      description: Ação para botão 2 single press
      default: []
      selector:
        action: null
    button_2_double:
      name: Double Press - Button 2
      description: Ação para botão 2 double press
      default: []
      selector:
        action: null
    button_2_hold:
      name: Hold - Button 2
      description: Ação para botão 2 hold
      default: []
      selector:
        action: null
    button_3_single:
      name: Single Press - Button 3
      description: Ação para botão 3 single press
      default: []
      selector:
        action: null
    button_3_double:
      name: Double Press - Button 3
      description: Ação para botão 3 double press
      default: []
      selector:
        action: null
    button_3_hold:
      name: Hold - Button 3
      description: Ação para botão 3 hold
      default: []
      selector:
        action: null
    button_4_single:
      name: Single Press - Button 4
      description: Ação para botão 4 single press
      default: []
      selector:
        action: null
    button_4_double:
      name: Double Press - Button 4
      description: Ação para botão 4 double press
      default: []
      selector:
        action: null
    button_4_hold:
      name: Hold - Button 4
      description: Ação para botão 4 hold
      default: []
      selector:
        action: null

mode: queued

trigger:
  - platform: event
    event_type: mqtt
    event_data:
      topic: "zigbee2mqtt/{{ switch }}/action"

action:
  - variables:
      command: "{{ trigger.event.data.payload }}"

  - choose:
      - conditions:
          - "{{ command == '1_single' }}"
        sequence: !input button_1_single
      - conditions:
          - "{{ command == '1_double' }}"
        sequence: !input button_1_double
      - conditions:
          - "{{ command == '1_hold' }}"
        sequence: !input button_1_hold
      - conditions:
          - "{{ command == '2_single' }}"
        sequence: !input button_2_single
      - conditions:
          - "{{ command == '2_double' }}"
        sequence: !input button_2_double
      - conditions:
          - "{{ command == '2_hold' }}"
        sequence: !input button_2_hold
      - conditions:
          - "{{ command == '3_single' }}"
        sequence: !input button_3_single
      - conditions:
          - "{{ command == '3_double' }}"
        sequence: !input button_3_double
      - conditions:
          - "{{ command == '3_hold' }}"
        sequence: !input button_3_hold
      - conditions:
          - "{{ command == '4_single' }}"
        sequence: !input button_4_single
      - conditions:
          - "{{ command == '4_double' }}"
        sequence: !input button_4_double
      - conditions:
          - "{{ command == '4_hold' }}"
        sequence: !input button_4_hold
