blueprint:
  name: Zigbee2MQTT - Tuya 1 to 4 Buttons
  description: Zigbee Tuya 1 to 4 Buttons
  domain: automation
  input:
    mode:
      name: Automation Modes
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    remote:
      name: Tuya button
      description: Works with 1-4 button remotes
      selector:
        entity:
          domain:
          - event
          multiple: true
    button_1_short_press:
      name: Single Press - Button 1
      description: Action to run on button 1 single press
      default: []
      selector:
        action: {}
    button_1_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 double press
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Hold - Button 1
      description: Action to run on button 1 hold press
      default: []
      selector:
        action: {}
    button_2_short_press:
      name: Single Press - Button 2
      description: Action to run on button 2 single press
      default: []
      selector:
        action: {}
    button_2_double_press:
      name: Double Press - Button 2
      description: Action to run on button 2 double press
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Hold - Button 2
      description: Action to run on button 2 hold press
      default: []
      selector:
        action: {}
    button_3_short_press:
      name: Single Press - Button 3
      description: Action to run on button 3 single press
      default: []
      selector:
        action: {}
    button_3_double_press:
      name: Double Press - Button 3
      description: Action to run on button 3 double press
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Hold - Button 3
      description: Action to run on button 3 hold press
      default: []
      selector:
        action: {}
    button_4_short_press:
      name: Single Press - Button 4
      description: Action to run on button 4 single press
      default: []
      selector:
        action: {}
    button_4_double_press:
      name: Double Press - Button 4
      description: Action to run on button 4 double press
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Long Press - Button 4
      description: Action to run on button 4 hold press
      default: []
      selector:
        action: {}
mode: !input mode
max_exceeded: silent
trigger:
  - platform: state
    entity_id: !input remote
condition:
  - "{{ trigger.to_state.attributes.event_type != '' }}"
action:
  - variables:
      event_type: "{{ trigger.to_state.attributes.event_type }}"
  - choose:
      - conditions:
          - "{{ event_type == '1_single' or event_type == 'single' }}"
        sequence: !input button_1_short_press
      - conditions:
          - "{{ event_type == '1_double' or event_type == 'double' }}"
        sequence: !input button_1_double_press
      - conditions:
          - "{{ event_type == '1_hold' or event_type == 'hold' }}"
        sequence: !input button_1_hold
      - conditions:
          - "{{ event_type == '2_single' }}"
        sequence: !input button_2_short_press
      - conditions:
          - "{{ event_type == '2_double' }}"
        sequence: !input button_2_double_press
      - conditions:
          - "{{ event_type == '2_hold' }}"
        sequence: !input button_2_hold
      - conditions:
          - "{{ event_type == '3_single' }}"
        sequence: !input button_3_short_press
      - conditions:
          - "{{ event_type == '3_double' }}"
        sequence: !input button_3_double_press
      - conditions:
          - "{{ event_type == '3_hold' }}"
        sequence: !input button_3_hold
      - conditions:
          - "{{ event_type == '4_single' }}"
        sequence: !input button_4_short_press
      - conditions:
          - "{{ event_type == '4_double' }}"
        sequence: !input button_4_double_press
      - conditions:
          - "{{ event_type == '4_hold' }}"
        sequence: !input button_4_hold
