blueprint:
  name: Zigbee2MQTT - TS044 4 Button
  description: Zigbee Tuya TS0044 4 Button
  domain: automation
  input:
    entity:
      name: Entity Action State
      selector:
        entity:
          domain: event
          integration: mqtt
          multiple: false

    # Button 1 Input Definition
    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on Button 1 - Single Press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button 1
      description: Action to run on Button 1 - Double Press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press - Button 1
      description: Action to run on Button 1 - Long Press
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input entity

action:
  - variables:
      event_type: "{{ trigger.event.data.action }}"
  - choose:
      - conditions:
          - "{{ event_type == '1_single' }}"
        sequence: !input button_one_short_press
      - conditions:
          - "{{ event_type == '1_double' }}"
        sequence: !input button_one_double_press
      - conditions:
          - "{{ event_type == '1_hold' }}"
        sequence: !input button_one_long_press
