blueprint:
  name: Zigbee2MQTT - TS044 4 Button
  description: Zigbee Tuya TS0044 4 Button
  domain: automation
  input:
    mqtt_entity:
      description: The "friendly" Tuya TS0044 4 Button device name as is registered in zigbee2mqtt
      name: Name
    base_topic:
      description: The base topic as defined in the zigbee2mqtt config
      default: zigbee2mqtt
      name: Base Topic
    state_entity:
      name: State
      selector:
        entity:
          domain: event
          integration: mqtt
          multiple: false

    # Button 1 Input Definition
    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on Button 1 - Single Press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button 1
      description: Action to run on Button 1 - Double Press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press - Button 1
      description: Action to run on Button 1 - Long Press
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  - platform: event
    event_type: button_one_action
    event_data:
      entity_id: !input mqtt_entity

action:
  - variables:
      event_type: "{{ trigger.event.data.action }}"
  - choose:
      - conditions:
          - "{{ event_type == '1_single' }}"
        sequence: !input button_one_short_press
      - conditions:
          - "{{ event_type == '1_double' }}"
        sequence: !input button_one_double_press
      - conditions:
          - "{{ event_type == '1_hold' }}"
        sequence: !input button_one_long_press
