blueprint:
  name: Zigbee2MQTT - Aqara Cube 
  description: Controls Aqara Cube through Zigbee2MQTT (support 12 actions)
  domain: automation
  input:
    mode:
      name: Automation Mode
      description: https://www.home-assistant.io/docs/automation/modes/
      default: single
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel

    remote:
      name: Aqara Cube
      description: Select the Aqara Cube action sensor
      selector:
        entity:
          domain:
            - event
          multiple: true          

    tap_on_side_0:
      name: Tap when side 0 selected
      default: []
      selector:
        action: {}
    tap_on_side_1:
      name: Tap when side 1 selected
      default: []
      selector:
        action: {}
    tap_on_side_2:
      name: Tap when side 2 selected
      default: []
      selector:
        action: {}
    tap_on_side_3:
      name: Tap when side 3 selected
      default: []
      selector:
        action: {}
    tap_on_side_4:
      name: Tap when side 4 selected
      default: []
      selector:
        action: {}
    tap_on_side_5:
      name: Tap when side 5 selected
      default: []
      selector:
        action: {}

    shake_on_side_0:
      name: Shake when side 0 selected
      default: []
      selector:
        action: {}
    shake_on_side_1:
      name: Shake when side 1 selected
      default: []
      selector:
        action: {}
    shake_on_side_2:
      name: Shake when side 2 selected
      default: []
      selector:
        action: {}
    shake_on_side_3:
      name: Shake when side 3 selected
      default: []
      selector:
        action: {}
    shake_on_side_4:
      name: Shake when side 4 selected
      default: []
      selector:
        action: {}
    shake_on_side_5:
      name: Shake when side 5 selected
      default: []
      selector:
        action: {}

mode: !input mode
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote

variables:
  event_type: "{{ trigger.to_state.attributes.event_type | default('') }}"
  side: >
    {% set side_sensor = 'sensor.' + trigger.entity_id.split('.')[-1] + '_side' %}
    {{ states(side_sensor) | int(0) }}

condition:
  - "{{ event_type != '' and side != -1 }}"

action:
  - choose:
      - conditions: "{{ event_type == 'tap' and side == 0 }}"
        sequence:
          - sequence: !input tap_on_side_0
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: tap | Side: 0"

      - conditions: "{{ event_type == 'tap' and side == 1 }}"
        sequence:
          - sequence: !input tap_on_side_1
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: tap | Side: 1"

      - conditions: "{{ event_type == 'tap' and side == 2 }}"
        sequence:
          - sequence: !input tap_on_side_2
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: tap | Side: 2"

      - conditions: "{{ event_type == 'tap' and side == 3 }}"
        sequence:
          - sequence: !input tap_on_side_3
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: tap | Side: 3"

      - conditions: "{{ event_type == 'tap' and side == 4 }}"
        sequence:
          - sequence: !input tap_on_side_4
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: tap | Side: 4"

      - conditions: "{{ event_type == 'tap' and side == 5 }}"
        sequence:
          - sequence: !input tap_on_side_5
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: tap | Side: 5"

      - conditions: "{{ event_type == 'shake' and side == 0 }}"
        sequence:
          - sequence: !input shake_on_side_0
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: shake | Side: 0"

      - conditions: "{{ event_type == 'shake' and side == 1 }}"
        sequence:
          - sequence: !input shake_on_side_1
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: shake | Side: 1"

      - conditions: "{{ event_type == 'shake' and side == 2 }}"
        sequence:
          - sequence: !input shake_on_side_2
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: shake | Side: 2"

      - conditions: "{{ event_type == 'shake' and side == 3 }}"
        sequence:
          - sequence: !input shake_on_side_3
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: shake | Side: 3"

      - conditions: "{{ event_type == 'shake' and side == 4 }}"
        sequence:
          - sequence: !input shake_on_side_4
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: shake | Side: 4"

      - conditions: "{{ event_type == 'shake' and side == 5 }}"
        sequence:
          - sequence: !input shake_on_side_5
          - action: logbook.log
            data:
              name: "Zigbee2MQTT - Aqara Cube"
              message: "Event: shake | Side: 5"

    default:
      - service: logbook.log
        data:
          name: "Zigbee2MQTT - Aqara Cube"
          message: "Event: {{ event_type }} | Side: {{ side }}"
